from typing import List, Optional, Tuple, Dict

MAX_LATITUDE: float
MAX_ZOOM: int

class Extent:
    def __init__(self, min_x: float, min_y: float, max_x: float, max_y: float) -> None: ...
    @staticmethod
    def parse(text: str) -> Extent: ...
    @property
    def min_x(self) -> float: ...
    @property
    def min_y(self) -> float: ...
    @property
    def max_x(self) -> float: ...
    @property
    def max_y(self) -> float: ...
    def width(self) -> float: ...
    def height(self) -> float: ...
    def is_valid(self) -> bool: ...
    def contains(self, x: float, y: float) -> bool: ...
    def intersects(self, other: Extent) -> bool: ...
    def to_tuple(self) -> Tuple[float, float, float, float]: ...
    def to_list(self) -> List[float]: ...

class Crs:
    def __init__(self, auth_id: str) -> None: ...
    @staticmethod
    def from_auth_id(auth_id: str) -> Crs: ...
    @staticmethod
    def from_epsg(code: int) -> Crs: ...
    @staticmethod
    def wgs84() -> Crs: ...
    @staticmethod
    def web_mercator() -> Crs: ...
    @property
    def auth_id(self) -> str: ...
    def name(self) -> Optional[str]: ...
    def is_geographic(self) -> bool: ...
    def is_projected(self) -> bool: ...

class Tile:
    def __init__(self, z: int, x: int, y: int) -> None: ...
    @staticmethod
    def from_lon_lat(z: int, lon: float, lat: float) -> Tile: ...
    @property
    def z(self) -> int: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    def bounds(self) -> Extent: ...

class ZoomRange:
    def __init__(self, min: int, max: int) -> None: ...
    @staticmethod
    def parse(text: str) -> ZoomRange: ...
    @property
    def min(self) -> int: ...
    @property
    def max(self) -> int: ...
    def count(self) -> int: ...

class ZoomLevelPlan:
    @property
    def zoom(self) -> int: ...
    @property
    def x_min(self) -> int: ...
    @property
    def x_max(self) -> int: ...
    @property
    def y_min(self) -> int: ...
    @property
    def y_max(self) -> int: ...
    def tile_count(self) -> int: ...

class TilePlan:
    def __init__(self, bounds: Extent, zooms: ZoomRange) -> None: ...
    @property
    def bounds(self) -> Extent: ...
    @property
    def zooms(self) -> ZoomRange: ...
    def level(self, zoom: int) -> ZoomLevelPlan: ...
    def levels(self) -> List[ZoomLevelPlan]: ...
    def tile_count(self) -> int: ...
    def iter_tiles(self) -> List[Tile]: ...

class Project:
    @staticmethod
    def open(path: str) -> Project: ...
    @property
    def path(self) -> str: ...
    @property
    def format(self) -> str: ...
    def info(self) -> ProjectInfo: ...
    def layers(self) -> List[LayerSummary]: ...
    def render(self, output: str, width: Optional[int] = ..., height: Optional[int] = ..., extent: Optional[Extent] = ..., crs: Optional[Crs] = ..., dpi: Optional[float] = ...) -> RenderedMap: ...

class ProjectInfo:
    @property
    def path(self) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def crs(self) -> Optional[Crs]: ...
    @property
    def layer_count(self) -> Optional[int]: ...
    @property
    def extent(self) -> Optional[Extent]: ...
    @property
    def note(self) -> Optional[str]: ...
    def to_dict(self) -> Dict: ...

class LayerSummary:
    @property
    def name(self) -> str: ...
    @property
    def provider(self) -> str: ...
    @property
    def crs(self) -> Optional[Crs]: ...
    @property
    def feature_count(self) -> Optional[int]: ...
    @property
    def geometry_type(self) -> Optional[str]: ...

class RenderedMap:
    @property
    def path(self) -> str: ...
    @property
    def bytes(self) -> int: ...

class RenderSettings:
    def __init__(self, output: str, width: int = 1024, height: int = 768, dpi: float = 96.0) -> None: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def dpi(self) -> float: ...
    def with_extent(self, extent: Extent) -> RenderSettings: ...
    def with_crs(self, crs: Crs) -> RenderSettings: ...
    def with_dpi(self, dpi: float) -> RenderSettings: ...
    def with_layers(self, layers: List[str]) -> RenderSettings: ...

def plan_tiles(bounds: str, zoom: str) -> Tuple[int, List[Tuple[int, int, int, int, int, int]]]: ...
def version() -> str: ...
