# Offline sandbox restore for Windows.
#
# This is the hand-ported twin of `scripts/restore.sh` (generated by
# `pixi-sandbox init` v0.4.3 on Linux). `init` only emits the launcher for the
# platform it runs on, so regenerate this natively rather than editing it:
#   pixi-sandbox init --project-root . --script-path scripts/restore.ps1
# …on Windows. Everything below matches restore.sh's decision order exactly:
# read the branch off the reviewed plan, fall back to a shallow fetch unless
# PIXI_SANDBOX_FETCH=skip, then hand the extracted transport to the binary the
# branch itself carries.
#
# The published plan declares linux-64 only, so this launcher needs a win-64
# bundle on the sandbox branch before it can restore anything — set
# PIXI_SANDBOX_BRANCH to point at one published out of band.
$ErrorActionPreference = 'Stop'
$Root = (git rev-parse --show-toplevel).Trim()
$Platform = 'win-64'
$DefaultBranch = 'sandbox/developer-win-64'
$Branch = $env:PIXI_SANDBOX_BRANCH
$Config = Join-Path $Root 'pixi-sandbox.toml'
if (-not $Branch -and (Test-Path $Config)) {
    # <branch_prefix>/<bundle>-<platform>, read off the same reviewed plan the publisher uses.
    $Text = Get-Content -Raw $Config
    $Prefix = if ($Text -match '(?m)^\s*branch_prefix\s*=\s*["'']([^"'']*)') { $Matches[1] } else { 'sandbox' }
    $Bundles = @()
    foreach ($Chunk in ($Text -split '\[\[\s*bundle\s*\]\]')) {
        if ($Chunk -match 'platforms[^\]]*["'']win-64["'']' -and $Chunk -match 'name\s*=\s*["'']([^"'']*)') {
            $Bundles += $Matches[1]
        }
    }
    if ($env:PIXI_SANDBOX_BUNDLE) { $Bundles = @($Bundles | Where-Object { $_ -eq $env:PIXI_SANDBOX_BUNDLE }) }
    if ($Bundles.Count -eq 1) {
        $Branch = "$Prefix/$($Bundles[0])-$Platform"
    } elseif ($Bundles.Count -gt 1) {
        Write-Error -Message "several bundles publish $Platform; set PIXI_SANDBOX_BUNDLE to choose" -ErrorAction Continue
    }
}
if (-not $Branch) { $Branch = $DefaultBranch }
# A missing local ref is fetched once, shallowly, rather than silently degrading
# to a full clone: `PIXI_SANDBOX_FETCH=skip` says the ref is already there.
$Ref = $Branch
git -C $Root rev-parse --verify "$Ref^{commit}" 2>$null | Out-Null
if ($LASTEXITCODE -ne 0) { $Ref = "origin/$Branch" }
git -C $Root rev-parse --verify "$Ref^{commit}" 2>$null | Out-Null
if ($LASTEXITCODE -ne 0) {
    if ($env:PIXI_SANDBOX_FETCH -eq 'skip') {
        Write-Error -Message "sandbox branch $Branch is not present locally (PIXI_SANDBOX_FETCH=skip); fetch refs/heads/sandbox/* before restoring"
        exit 2
    }
    git -C $Root fetch --depth 1 origin "refs/heads/$Branch`:refs/remotes/origin/$Branch"
    if ($LASTEXITCODE -ne 0) {
        Write-Error -Message "cannot fetch $Branch from origin; run: git fetch origin 'refs/heads/sandbox/*:refs/remotes/origin/sandbox/*'"
        exit 2
    }
    $Ref = "origin/$Branch"
}
$Transport = Join-Path $Root '.pixi/.restore-transport'
Remove-Item -Recurse -Force $Transport -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Force $Transport | Out-Null
git -C $Root archive --format=tar $Ref | tar -xf - -C $Transport
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
$Binary = Join-Path $Transport ".pixi-sandbox/tools/$Platform/pixi-sandbox.exe"
# User-tool registration is selected by environment variable, never a flag: the
# binary this script executes comes from the packed branch, which may predate
# --user-tools, and an unknown variable is ignored where an unknown flag is a
# hard error. Default matches restore.sh (`register`); a locked-down host sets
# PIXI_SANDBOX_USER_TOOLS=skip. A trailing --user-tools argument still wins,
# because later arguments override the environment.
if (-not $env:PIXI_SANDBOX_USER_TOOLS) { $env:PIXI_SANDBOX_USER_TOOLS = 'register' }
& $Binary restore --branch-location $Transport --output-path $Root --force @args
exit $LASTEXITCODE